version: '3'
services:
  web:
    image: codeship-python-django-todoapp_web.slim
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: healthcheck/postgres:alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
      POSTGRES_HOST_AUTH_METHOD: trust